CREATE TABLE IF NOT EXISTS students (
    id                BINARY(16)    PRIMARY KEY NOT NULL,
    first_name        VARCHAR(255)  NOT NULL,
    middle_name       VARCHAR(255)  DEFAULT '',
    last_name         VARCHAR(255)  NOT NULL,
    extension_name    VARCHAR(50)   DEFAULT '',
    email             VARCHAR(255)  NOT NULL UNIQUE,
    password          VARCHAR(255)  NOT NULL,
    school_id         BIGINT        NOT NULL,
    lrn               VARCHAR(20)   DEFAULT '',
    date_of_birth     DATE          NULL,
    place_of_birth    VARCHAR(255)  DEFAULT '',
    sex               ENUM('male','female') NOT NULL DEFAULT 'male',
    nationality       VARCHAR(100)  DEFAULT 'Filipino',
    region            VARCHAR(255)  DEFAULT '',
    province          VARCHAR(255)  DEFAULT '',
    city_municipality VARCHAR(255)  DEFAULT '',
    barangay          VARCHAR(255)  DEFAULT '',
    purok_street      VARCHAR(255)  DEFAULT '',
    contact_number    VARCHAR(255)  DEFAULT NULL,
    admin_id          BINARY(16)    NOT NULL,
    created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_students_school_id (school_id)
);
